GET http://localhost:5091/games
###
GET http://localhost:5091/games/2
###
POST http://localhost:5091/games
Content-Type: application/json

{
    "name": "Stardew Valley",
    "gender": "Simulation",
    "price": 14.99,
    "releaseDate": "2016-02-26"
}

###
PUT http://localhost:5091/games/2
Content-Type: application/json

{
    "name": "Stardew Dava",
    "gender": "Simulation",
    "price": 14.99,
    "releaseDate": "2016-02-26"
}

###
DELETE http://localhost:5091/games/6
